apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/displayName: CICS Ansible Runner Task
  name: cics-ansible-runner-task
  namespace: cics-pipeline-demo
spec:
  description: Task to run Ansible playbooks using the Ansible Operator image
  params:
    - default:
        - ansible-playbook
        - '--help'
      description: The arguments to pass ansible-runner
      name: args
      type: array
  steps:
    - name: ansible
      image: quay.io/ivandov1/cics-pipeline-demo-ansible
      command:
        - $(params.args)
      # command: [ "/bin/bash", "-c", "--" ]
      # args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: tekton-key
          mountPath: /opt/ansible
      resources: {}
      workingDir: $(workspaces.ansible.path)
  workspaces:
    - description: The Ansible directory
      name: ansible
  volumes:
  - name: tekton-key
    secret:
      secretName: tekton-key
      items:
      - key: ssh-privatekey
        path: .ssh/id_rsa
