kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cics-pipeline-demo-pvc
  namespace: cics-pipeline-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage

