kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cics-pipeline-demo-eventlistener
spec:
  to:
    kind: Service
    name: el-cics-pipeline-demo
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
