PYZ: /usr/lpp/IBM/cyp/v3r8/pyz
ZOAU: /usr/lpp/IBM/zoautil

system_environment:
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _BPXK_AUTOCVT: "ON"
  _BPXK_JOBLOG: STDERR
  _BPXK_SHAREAS: "YES"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:/usr/sbin"


################################################################################
# CMCI information
################################################################################
# Target CMCI hostname
cmci_host: 129.40.130.49

# Target CMCI port
cmci_port: 2490

# CMCI scheme (http or https)
scheme: http

# Target CICSplex SM context
# For SMSS use applid of the CICS region
context: CICSOCP1

# Target CICSplex SM scope (probably the target region name)
scope: CICSOCP1

# Name of the target program
program: DFH0XVDS

# Name of the data set containing the build output load module
# build_ds: ????????

# Name of the destination load library for the load module
load_lib: CICSTS.CICS.DEMOLOAD

# CMCI user name (leave blank for unauthenticated)
cmci_user:

# CMCI password (leave blank for unauthenticated)
cmci_password:
