apiVersion: v1
kind: Pod
metadata:
  name: cics-pipeline-demo-ansible-runner
spec:
  containers:
    - name: cics-pipeline-demo-ansible-runner
      image: sys-zoscb-docker-local.artifactory.swg-devops.com/cics/pipeline-demo-ansible-runner:latest
      # Just spin & wait forever
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
      - name: workspace-pvc
        mountPath: /workspace/ansible
  volumes:
    - name: workspace-pvc
      persistentVolumeClaim:
        claimName: cics-pipeline-demo-pvc
