apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cics-pipeline-demo-debug
  annotations:
    pipeline.openshift.io/started-by: admin
  namespace: cics-pipeline-demo
  labels:
    tekton.dev/pipeline: cics-pipeline-demo
spec:
  params:
    - name: repo-url
      value: git@github.ibm.com:IBMZSoftware/CloudBroker-OSDemo.git
    - name: branch-name
      value: demo
  pipelineRef:
    name: cics-pipeline-demo
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: cics-pipeline-demo-pvc