apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: ansible-runner-debugger
  namespace: cics-pipeline-demo
spec:
  params:
    - name: args
      value:
        - ls
        - '-lah'
  resources: {}
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: cics-ansible-runner-task
  timeout: 1h0m0s
  workspaces:
    - name: ansible
      persistentVolumeClaim:
        claimName: cics-pipeline-demo-pvc
